# Generated by Django 4.1.3 on 2022-11-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('lecturer', models.CharField(max_length=100)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('face_images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('note_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('note_title', models.CharField(max_length=100)),
                ('note_type', models.CharField(max_length=100)),
                ('note_link', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
            ],
        ),
        migrations.CreateModel(
            name='LoginHist',
            fields=[
                ('login_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('time_stayed', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('classroom', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('duration', models.FloatField()),
                ('message', models.TextField()),
                ('zoom_link', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
            ],
        ),
    ]
